version: '3.7'

services:

  web-app:
    container_name: github-issues-app
    build:
      context: .
      target: development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
